---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

## Introduction 
Climate change is altering many ecosystem functions on a global scale. Biological communities are predicted to experience dynamic shifts as increased temperatures and frequency of severe weather events, both of which are linked with increasing temperatures, cause drastic changes of ecosystem structure (Kerby & Wilmers, 2012). This will most likely manifest through disruptions of trophic level interactions, including predator-prey relationships.

Increasing temperatures impact many aspects of freshwater ecosystems, including (Woodward, Perkins & Brown, 2010) (Elliot, 2012) (Mooij et al., 2005) (Johnston & Dunn, 1987).

 * Stratification patterns
 * Environmental health of biological communities, 
 * Increased metabolic rates, 
 * Physical water properties, 
 * Lake mixing frequency, and 
 * Nutrient flow to organisms 

All these factors directly impact the livelihoods of organisms and the niches they occupy. Species must be able to adapt to these new niches or they will suffer from lack of access to adequate food, shelter, or other. Aquatic communities are at a heightened risk for experiencing changes from anthropogenic-linked climate change, particularly water bodies that have been greatly altered through human disruption (Grimm et al., 1997). The American Southwest, famous for harnessing large amounts of water for crop irrigation or hydroelectric power generation, is full of prime examples of practices that are deleterious to aquatic ecosystems. 

Lake Powell is one case of such a system. Located on the border of Utah and Arizona, Powell was constructed in the middle of the 20th century by damming a section of the Colorado River in the Glen Canyon. The construction of the Glen Canyon Dam resulted in the eventual flooding of the depression, forming present-day Lake Powell. Currently, the reservoir is highly utilized for recreation and thus is managed largely to prioritize the experience of consumers visiting this reservoir (Douglas & Harpman, 2009). As this ecosystem is not managed to benefit aquatic ecosystem health, biological communities present are liable to suffer from climate change related issues.

As ecosystems become more dynamic, changing phenologies of biological activities is liable to become more prevalent. Different trophic levels do not always change phenologies at the same rate in response to changing environmental conditions, resulting in species blooms occurring at different times (Durant et al., 2007). Temporal mis-matches affect both aquatic and terrestrial ecosystems, with advancing appearance of primary producers resulting in under-exploitation of total available food resources by higher trophic levels (Colebrook, 1979). This has been observed repeatedly, with fluctuations of fish, birds and other aquatic predators being linked with variation of food availability (Fortier et al., 1995; Thackeray et al., 2010; Burthe et al., 2012; Thackeray et al., 2016; Keogan et al., 2018). Inadequate responses of higher trophic levels to follow phenological changes of lower trophic levels jeopardizes their livelihood, posing negative effects to growth, reproduction, and mortality of these organisms (Keogan et al., 2018).

Increasing temperatures are causing advancing phenological changes in the spring and summer in many aquatic ecosystems (Thackeray et al., 2010; Thackeray et al., 2016). Photosynthetic phytoplankton are blooming earlier in the spring in response to increasing temperatures and nutrient levels, coupled with favorable low light conditions (Robarts & Zohary, 1978; Reynolds, 1984; Thackeray et al., 2012). Earlier thermal stratification in freshwater lakes is the mechanism driving advancing algal phenology, resulting in preferable water conditions for spring-blooming algal communities occurring earlier in the spring (Winder & Schindler, 2004). 

In lake communities, the primary consumer trophic level is composed of zooplankton, including rotifers, cladocerans, and copepods. Timing of the presence of cladocerans and copepods are largely regulated by other changing environmental cues, primarily the photoperiod (Stross, 1966). Copepoda and cladocera are much more nutritive food sources for higher trophic levels, indicating that they play key link in transferring energy from phytoplankton to insectivorous fish (Fernando, 1994). As the timing of algal blooms advances while blooms of cladocera and copepoda stay constant, there is the potential for a temporal mismatch between when phytoplankton and trophically important zooplankton are present that will not be remediated by evolutionary adaptations to changing phonologies of phytoplankton blooms. If algae bloom earlier in the season in lower-light conditions and then taper off before light conditions are fit for hatches of cladocera or copepoda, these two zooplankton groups will suffer due to reduced food sources in the water column. This mismatch of algal and zooplankton communities will likely impact overall ecosystem biodiversity and biomass of specific species due to bottom-up effects.

Zooplankton and phytoplankton population in Lake Mead, another reservoir on the Colorado River located in the American Southwest, were observed recently but found to be stable during the monitoring period, spanning from 2007 to 2015 (Beaver et al., 2018). The populations in Mead have persisted through invasion of foreign species, increased water demand from the reservoir and environmental stresses including drought and increased temperatures, indicating population dynamics resilient to global climate change. Thus, there was no temporal mismatch between zooplankton and their main food source in this similar water body. Observing how phytoplankton and zooplankton communities in Lake Powell have responded to current stresses will offer insight into how they will respond as environmental conditions become exacerbated in the future. Insight into these relationships will also identify whether or not a temporal mismatch is occurring in this reservoir, posing a threat to higher trophic levels and potentially detracting from the cultural values of this ecosystem.

*** 

Visit this [page](https://ssoba.github.io/lake_powell/) for the full list of references
